default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: nosql
  host: localhost

development:
  <<: *default
  database: ruby_doctor_hunt

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
